dmflakey: support external log and realtime devices
Upgrade the dmerror code to coordinate making external scratch log and
scratch realtime devices error out along with the scratch device.

Signed-off-by: Darrick J. Wong <darrick.wong@oracle.com>

diff --git a/common/dmerror b/common/dmerror
--- a/common/dmerror
+++ b/common/dmerror
@@ -6,28 +6,58 @@
 
 _dmerror_setup()
 {
+	# Scratch device
 	local dm_backing_dev=$SCRATCH_DEV
-
 	local blk_dev_size=`blockdev --getsz $dm_backing_dev`
-
 	DMERROR_DEV='/dev/mapper/error-test'
-
 	DMLINEAR_TABLE="0 $blk_dev_size linear $dm_backing_dev 0"
-
 	DMERROR_TABLE="0 $blk_dev_size error $dm_backing_dev 0"
+
+	# Realtime device
+	if [ -n "$SCRATCH_RTDEV" ]; then
+		local dm_backing_dev=$SCRATCH_RTDEV
+		local blk_dev_size=`blockdev --getsz $dm_backing_dev`
+		DMERROR_RTDEV='/dev/mapper/error-rttest'
+		DMLINEAR_RTTABLE="0 $blk_dev_size linear $dm_backing_dev 0"
+		DMERROR_RTTABLE="0 $blk_dev_size error $dm_backing_dev 0"
+	fi
+
+	# External log device
+	if [ -n "$SCRATCH_LOGDEV" ]; then
+		local dm_backing_dev=$SCRATCH_LOGDEV
+		local blk_dev_size=`blockdev --getsz $dm_backing_dev`
+		DMERROR_LOGDEV='/dev/mapper/error-logtest'
+		DMLINEAR_LOGTABLE="0 $blk_dev_size linear $dm_backing_dev 0"
+		DMERROR_LOGTABLE="0 $blk_dev_size error $dm_backing_dev 0"
+	fi
 }
 
 _dmerror_init()
 {
 	_dmerror_setup
+
 	_dmsetup_remove error-test
 	_dmsetup_create error-test --table "$DMLINEAR_TABLE" || \
 		_fatal "failed to create dm linear device"
+
+	if [ -n "$DMERROR_RTDEV" ]; then
+		_dmsetup_remove error-rttest
+		_dmsetup_create error-rttest --table "$DMLINEAR_RTTABLE" || \
+			_fatal "failed to create dm linear rt device"
+	fi
+
+	if [ -n "$DMERROR_LOGDEV" ]; then
+		_dmsetup_remove error-logtest
+		_dmsetup_create error-logtest --table "$DMLINEAR_LOGTABLE" || \
+			_fatal "failed to create dm linear log device"
+	fi
 }
 
 _dmerror_mount()
 {
-	_scratch_options mount
+	SCRATCH_LOGDEV=$DMERROR_LOGDEV SCRATCH_RTDEV=$DMERROR_RTDEV \
+		_scratch_options mount
+
 	$MOUNT_PROG -t $FSTYP `_common_dev_mount_options $*` $SCRATCH_OPTIONS \
 		$DMERROR_DEV $SCRATCH_MNT
 }
@@ -41,6 +71,9 @@ _dmerror_cleanup()
 {
 	$DMSETUP_PROG resume error-test > /dev/null 2>&1
 	$UMOUNT_PROG $SCRATCH_MNT > /dev/null 2>&1
+
+	test -n "$DMERROR_LOGDEV" && _dmsetup_remove error-logtest
+	test -n "$DMERROR_RTDEV" && _dmsetup_remove error-rttest
 	_dmsetup_remove error-test
 }
 
@@ -57,11 +90,46 @@ _dmerror_load_error_table()
 		suspend_opt="$*"
 	fi
 
+	# Suspend the scratch device before the log and realtime devices so
+	# that the kernel can freeze and flush the filesystem if the caller
+	# wanted a freeze.
 	$DMSETUP_PROG suspend $suspend_opt error-test
 	[ $? -ne 0 ] && _fail  "dmsetup suspend failed"
 
+	if [ -n "$DMERROR_RTDEV" ]; then
+		$DMSETUP_PROG suspend $suspend_opt error-rttest
+		[ $? -ne 0 ] && _fail "failed to suspend error-rttest"
+	fi
+
+	if [ -n "$DMERROR_LOGDEV" ]; then
+		$DMSETUP_PROG suspend $suspend_opt error-logtest
+		[ $? -ne 0 ] && _fail "failed to suspend error-logtest"
+	fi
+
+	# Load new table
 	echo "$DMERROR_TABLE" | $DMSETUP_PROG load error-test
 	load_res=$?
+
+	if [ -n "$DMERROR_RTDEV" ]; then
+		$DMSETUP_PROG load error-rttest --table "$DMERROR_RTTABLE"
+		[ $? -ne 0 ] && _fail "failed to load error table into error-rttest"
+	fi
+
+	if [ -n "$DMERROR_LOGDEV" ]; then
+		$DMSETUP_PROG load error-logtest --table "$DMERROR_LOGTABLE"
+		[ $? -ne 0 ] && _fail "failed to load error table into error-logtest"
+	fi
+
+	# Resume devices in the opposite order that we suspended them.
+	if [ -n "$DMERROR_LOGDEV" ]; then
+		$DMSETUP_PROG resume error-logtest
+		[ $? -ne 0 ] && _fail  "failed to resume error-logtest"
+	fi
+
+	if [ -n "$DMERROR_RTDEV" ]; then
+		$DMSETUP_PROG resume error-rttest
+		[ $? -ne 0 ] && _fail  "failed to resume error-rttest"
+	fi
 
 	$DMSETUP_PROG resume error-test
 	resume_res=$?
@@ -83,11 +151,46 @@ _dmerror_load_working_table()
 		suspend_opt="$*"
 	fi
 
+	# Suspend the scratch device before the log and realtime devices so
+	# that the kernel can freeze and flush the filesystem if the caller
+	# wanted a freeze.
 	$DMSETUP_PROG suspend $suspend_opt error-test
 	[ $? -ne 0 ] && _fail  "dmsetup suspend failed"
 
+	if [ -n "$DMERROR_RTDEV" ]; then
+		$DMSETUP_PROG suspend $suspend_opt error-rttest
+		[ $? -ne 0 ] && _fail "failed to suspend error-rttest"
+	fi
+
+	if [ -n "$DMERROR_LOGDEV" ]; then
+		$DMSETUP_PROG suspend $suspend_opt error-logtest
+		[ $? -ne 0 ] && _fail "failed to suspend error-logtest"
+	fi
+
+	# Load new table
 	$DMSETUP_PROG load error-test --table "$DMLINEAR_TABLE"
 	load_res=$?
+
+	if [ -n "$DMERROR_RTDEV" ]; then
+		$DMSETUP_PROG load error-rttest --table "$DMLINEAR_RTTABLE"
+		[ $? -ne 0 ] && _fail "failed to load working table into error-rttest"
+	fi
+
+	if [ -n "$DMERROR_LOGDEV" ]; then
+		$DMSETUP_PROG load error-logtest --table "$DMLINEAR_LOGTABLE"
+		[ $? -ne 0 ] && _fail "failed to load working table into error-logtest"
+	fi
+
+	# Resume devices in the opposite order that we suspended them.
+	if [ -n "$DMERROR_LOGDEV" ]; then
+		$DMSETUP_PROG resume error-logtest
+		[ $? -ne 0 ] && _fail  "failed to resume error-logtest"
+	fi
+
+	if [ -n "$DMERROR_RTDEV" ]; then
+		$DMSETUP_PROG resume error-rttest
+		[ $? -ne 0 ] && _fail  "failed to resume error-rttest"
+	fi
 
 	$DMSETUP_PROG resume error-test
 	resume_res=$?
@@ -155,20 +258,35 @@ __dmerror_recreate_map()
 # Update the dm error table so that the range (start, len) maps to the
 # preferred dm target, overriding anything that maps to the implied dm target.
 # This assumes that the only desired targets for this dm device are the
-# preferred and and implied targets.
+# preferred and and implied targets.  The fifth argument is the scratch device
+# that we want to change the table for.
 __dmerror_change()
 {
 	local start="$1"
 	local len="$2"
 	local preferred_tgt="$3"
 	local implied_tgt="$4"
+	local whichdev="$5"
 
-	DMERROR_TABLE="$( (echo "$DMERROR_TABLE"; echo "$start $len $preferred_tgt") | \
+	case "$whichdev" in
+	""|"$SCRATCH_DEV")	old_table="$DMERROR_TABLE";;
+	"$SCRATCH_LOGDEV")	old_table="$DMERROR_LOGTABLE";;
+	"$SCRATCH_RTDEV")	old_table="$DMERROR_RTTABLE";;
+	*)			echo "$whichdev: Unknown dmerror device."; return;;
+	esac
+
+	new_table="$( (echo "$old_table"; echo "$start $len $preferred_tgt") | \
 		awk -v type="$preferred_tgt" '{if ($3 == type) print $0;}' | \
 		sort -g | \
 		__dmerror_combine_extents | \
 		__dmerror_recreate_map "$SCRATCH_DEV" "$preferred_tgt" \
 				"$implied_tgt" )"
+
+	case "$whichdev" in
+	""|"$SCRATCH_DEV")	DMERROR_TABLE="$new_table";;
+	"$SCRATCH_LOGDEV")	DMERROR_LOGTABLE="$new_table";;
+	"$SCRATCH_RTDEV")	DMERROR_RTTABLE="$new_table";;
+	esac
 }
 
 # Reset the dm error table to everything ok.  The dm device itself must be
@@ -184,8 +302,9 @@ _dmerror_mark_range_bad()
 {
 	local start="$1"
 	local len="$2"
+	local dev="$3"
 
-	__dmerror_change "$start" "$len" error linear
+	__dmerror_change "$start" "$len" error linear "$dev"
 }
 
 # Update the dm error table so that IOs to the given range will succeed.
@@ -194,6 +313,7 @@ _dmerror_mark_range_good()
 {
 	local start="$1"
 	local len="$2"
+	local dev="$3"
 
-	__dmerror_change "$start" "$len" linear error
+	__dmerror_change "$start" "$len" linear error "$dev"
 }
