xfs: stop online repair fuzz test if mount fails
If we're doing a fuzz test for how online scrub and repair react to a
corrupted field/value and the mount fails, we can't actually try the
repair.  In that case, the only thing we still need to check is that
xfs_repair will also catch the fuzzed field.

Signed-off-by: Darrick J. Wong <darrick.wong@oracle.com>

diff --git a/common/fuzzy b/common/fuzzy
--- a/common/fuzzy
+++ b/common/fuzzy
@@ -211,7 +211,16 @@ __scratch_xfs_fuzz_field_test() {
 		fi
 
 		__scratch_xfs_fuzz_unmount
-	elif [ "${repair}" = "online" ] || [ "${repair}" = "both" ]; then
+	elif [ "${repair}" = "online" ]; then
+		(>&2 echo "mount failed ($res) with ${field} = ${fuzzverb}, cannot make further progress.")
+
+		echo "+ Make sure corruption is detected by offline repair"
+		_scratch_xfs_repair -n 2>&1
+		res=$?
+		test $res -ne 0 && \
+			(>&2 echo "offline scrub ($res) with ${field} = ${fuzzverb}.")
+		return
+	elif [ "${repair}" = "both" ]; then
 		(>&2 echo "mount failed ($res) with ${field} = ${fuzzverb}.")
 	fi
 
