xfs: test new xfs_healer daemon
Make sure the daemon in charge of self healing xfs actually does what it
says it does -- emits json blobs that can be validated against the
schema, repairs metadata, logs file IO errors, and doesn't get
overwhelmed by event floods.

Signed-off-by: "Darrick J. Wong" <djwong@kernel.org>

diff --git a/common/xfs b/common/xfs
--- a/common/xfs
+++ b/common/xfs
@@ -2274,3 +2274,53 @@ _scratch_find_rt_metadir_entry() {
 
 	return 1
 }
+
+# Run the xfs_healer self healing daemon
+_scratch_xfs_healer() {
+	local healer_args=()
+	local daemon_dir
+	daemon_dir=$(dirname "$XFS_HEALER_PROG")
+
+	# If we're being run from a development branch, we might need to find
+	# the schema file on our own.
+	local maybe_schema="$daemon_dir/../libxfs/xfs_healthmon.schema.json"
+	if [ -f "$maybe_schema" ]; then
+		healer_args+=(--event-schema "$maybe_schema")
+	fi
+
+	$XFS_HEALER_PROG "${healer_args[@]}" "$@" $SCRATCH_MNT
+}
+
+# Turn off the background xfs_healer service if any so that it doesn't fix
+# injected metadata errors; then start a background copy of xfs_healer to
+# capture that.  Note that unmounting the scratch fs causes the healer daemon
+# to exit, so we don't need to kill it explicitly from _cleanup.
+_scratch_invoke_healer() {
+	local logfile="$1"
+	shift
+
+	if _systemd_is_running; then
+		local scratch_path=$(systemd-escape --path "$SCRATCH_MNT")
+		_systemd_unit_stop "xfs_healer@${scratch_path}" &>> $seqres.full
+	fi
+
+	_scratch_xfs_healer "$@" > "$logfile" &
+	SCRATCH_HEALER_PID=$!
+	sleep 1
+}
+
+# Unmount the filesystem to kill the xfs_healer instance started by
+# _scratch_invoke_healer, and wait for it to exit.
+_scratch_kill_healer() {
+	local unmount="${1:-_scratch_unmount}"
+
+	# Unmount fs to kill healer, then wait for it to finish
+	while ! $unmount &>/dev/null; do
+		sleep 0.5
+	done
+
+	test -n "$SCRATCH_HEALERPID" && \
+		kill $SCRATCH_HEALER_PID &>> $seqres.full
+	wait
+	unset SCRATCH_HEALER_PID
+}
